export const CLEAR_LIST = 'CLEAR_LIST'
export const RESET_LIST = 'RESET_LIST'
export const REMOVE = 'REMOVE '
export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'
export const LOADING = 'LOADING'
export const DISPLAY_ITEMS = 'DISPLAY_ITEMS'
